### ISSUE TITLE
Boer Republic decision still broken, includes bug analysis and proposed fix

### ISSUE THREAD

**Issue by Sun-Wu** [Victoria2CoE/concert-of-europe#28]
potential = {
			OR = {
				tag = TRN
				primary_culture = boer
				year = 1860
				has_global_flag = boer_covention_denied
			}
			NOT = { has_country_flag = republic_founded }
		}

The reason for it appearing for other countries is the OR condition, in this case if the year is 1860 ANY country that doesn't have the country flag republic founded can see the decision.

Proposed fix
OR = {
tag = TRN
primary_culture = boer
}
OR = {
year = 1860
has_global_flag = boer_covention_denied
}
By breaking it up into two OR checks it means reaching the year 1860 won't automatically make the decision appear for Sikkim or what have you. Note, I don't actually know if there is a point to having tag = TRN and primary_culture = boer, perhaps just one or the other depending on what you desire?

**Comment by GeneralVonGelre** [comment]
Fixed!
