### ISSUE TITLE
Accidental importation of mod file for Beta

### ISSUE THREAD

**Issue by Sun-Wu** [Victoria2CoE/concert-of-europe#29]
The mod file was merged in from the Beta branch, but as the path wasn't changed it doesn't load the mod because it looks in "mod/Concert_Beta" but the mod is actually at "mod/PDM_Concert"

**Comment by GeneralVonGelre** [comment]
Shouldn't have been merged, have since requested the person causing this to please stop editing the .mod file, will be fixed asap
