### ISSUE TITLE
France not going after Algeria; FRA event 37234 The Fan Affair

### ISSUE THREAD

**Issue by crownsteler** [Victoria2CoE/concert-of-europe#34]
Some people may have noticed that France sometimes (often?) doesn't go after Algeria. This is due to a change I accidentally introduced earlier in the development of CoE when I optimised the French events created by Shin. I thought I had fixed it back then, but apparently I did not.

Anyway, here is the issue.
Event 37234 (The Fan Affair) starts the French conquest of Algeria. Without this event firing France will not go after Algeria (creating a rather weird world). This event will not always fire because the trigger requires the country flag "charles_x" for France, but event 37244 (July Revolution) removes this flag from France. Event 37244 has a tendency to fire before 37234 (due to MTTH modifiers).

Easiest solution would be to either remove this line from event 37244:
`clr_country_flag = charles_x`

Or change the trigger of event 37234 to this:
`

> trigger = {
> 		tag = FRA
> 		exists = yes
> 		OR = {
> 			has_country_flag = charles_x
> 			has_country_flag = july_revolution
> 		}
> 		NOT = {
> 			year = 1836
> 			truce_with = ALD
> 		}
> 		ALD = {
> 			exists = yes
> 			civilized = no
> 		}
> 	}

`

**Comment by GeneralVonGelre** [comment]
Fixed.
