### ISSUE TITLE
French presence in Libreville

### ISSUE THREAD

**Issue by megaspider01** [Victoria2CoE/concert-of-europe#43]
While reading a book about empires they started talking about the returning of Africans to Africa and one example being Libreville, which was founded by slaves freed by the French in 1849. Further reading showed that there already was a French presence there in 1839. I propose an event for the French to gain the province of Libreville in either 1839 or 1849 to represent this and also to give the colonization of Africa more flavour (still lacking IMO).

**Comment by cijik** [comment]
Added the event (37299)
