### ISSUE TITLE
German formation issues

### ISSUE THREAD

**Issue by Sun-Wu** [Victoria2CoE/concert-of-europe#55]
1) Switzerland can form Germany (hard, but a Germany that has French and Italian as accepted can be terrifying)
2) Switzerland can get inherited via German formation events
3) Banat Republic can also be inherited via German formation events

**Comment by cijik** [comment]
In this case, how should I approach the issue with Banat Republic. Change the primary culture to Romanian/Serbian or remove the tag altogether?

**Comment by Sun-Wu** [comment]
Just remove the Banat Republic
