### ISSUE TITLE
Page 9 Ledger CtD

### ISSUE THREAD

**Issue by Sun-Wu** [Victoria2CoE/concert-of-europe#56]
Ho (#1915) has horses as a trade good, in game this shows as no good and I think it is causing the crash on page 9 of the ledger.

**Comment by cijik** [comment]
Kind of strange. Horses exist as a trade good and the history entry for the province has the trade_goods value valid.

**Comment by Sun-Wu** [comment]
The issue is there is not an RGO entry in the \common\production_types.txt, this can be resolved by adding this code to the file

horse_breeder = {
	template = RGO_template_farmers
	output_goods = horses
	value = 5
	farm = yes
}

Either way, it should be removed because the horse RGO is too inefficient and by mid game is almost always at 100% unemployment.

**Comment by GeneralVonGelre** [comment]
solved by letting the province produce something else (?)
