### ISSUE TITLE
Persia

### ISSUE THREAD

**Issue by Sun-Wu** [Victoria2CoE/concert-of-europe#67]
1) the event "The Tobacco Protests" has numerous typographical errors, "threatend" should be "threatened", "en mass" should be "en masse", "livelyhood" should be livelihood", "no sworn" should probably by "now sworn", "extend" should be "extent", "servents" should be "servants".
2) The aforementioned event can repeatedly fire if one bows to the almighty dollar
3) Mousing over the trigger for the persian_caucasus decision in irredentism.txt causes a crash because it checks for AFG_1214 which no longer exists

**Comment by ckanbak** [comment]
The alternative Treaty of Erzurum event (id = 300986) is horribly broken. 
    1. It does not end the war between Ottomans and Persia, simply cedes the provinces.
    2. The provinces are ceded only if Ottomans control them directly. In the beginning, they are 
        controlled by Iraq, which means there is no province exchange.
So basically, the event does not do anything it is intended for.

**Comment by cijik** [comment]
Fixed the persian_caucasus trigger and pushed a possible fix to the alternative Treaty of Erzurum

**Comment by cijik** [comment]
Fixed typos. It seems the event firing repeatedly is intended, since there's a specific modifier to MTTH that makes it fire less often if the second option was chosen. Maybe tune up the modifier so it fires even less often?
