### ISSUE TITLE
Austria has defunct (?) "North German" culture as primary culture

### ISSUE THREAD

**Issue by JamesBagley** [Victoria2CoE/concert-of-europe#82]
Starting a game as Austria the player/AI has 0 accepted or primary pops as there are no "North Germans" only "Germans", makes it impossible to get more than one national focus or to recruit artillery & regulars until forming Austria-Hungary, at which point Hungarian becomes an accepted culture.

**Comment by Mitusonator** [comment]
yes yes, I fixed it
